from __future__ import annotations

from .analysis_evidence_constraint_models import EvidenceConstraint, _inventory


def _waxs_constraint_inventory() -> list[EvidenceConstraint]:
    return _inventory(
        EvidenceConstraint(
            name="peak_visibility",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Missing sharp peaks weaken crystallinity claims.",
            field="n_peaks",
            rationale="Crystallinity should be supported by visible peak structure.",
        ),
        EvidenceConstraint(
            name="temperature_axis_missing",
            kind="hard_fail",
            source="WAXS",
            severity="ERROR",
            description="In-situ WAXS sequence is missing a reliable temperature axis.",
            field="temperature_missing_count",
            rationale="Temperature trends cannot be trusted if the axis itself is missing or incomplete.",
        ),
        EvidenceConstraint(
            name="temperature_axis_low_confidence",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="The temperature axis is present but still low-confidence.",
            field="condition_confidence",
            rationale="Sequence interpretation should remain provisional until the temperature axis stabilizes.",
        ),
        EvidenceConstraint(
            name="temperature_sequence_nonmonotonic",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Temperature sequence is not strictly monotonic.",
            field="temperature_monotonic",
            rationale="Heating or cooling order must be clear before a trend is interpreted.",
        ),
        EvidenceConstraint(
            name="temperature_duplicate_frames",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Duplicate temperature frames weaken sequence continuity.",
            field="temperature_duplicate_count",
            rationale="Duplicate conditions can fake smooth trends.",
        ),
        EvidenceConstraint(
            name="peak_count_insufficient",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Too few resolved peaks make phase and size claims fragile.",
            field="n_peaks",
            rationale="A stable crystal family usually needs at least two resolved peaks.",
        ),
        EvidenceConstraint(
            name="peak_family_unstable",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Peak positions or widths drift too much for a stable crystal family.",
            field="peaks",
            rationale="Peak positions and widths should move together rather than fragmenting into unrelated components.",
        ),
        EvidenceConstraint(
            name="amorphous_partition_unstable",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Crystallinity depends too much on amorphous partitioning.",
            field="Xc_method",
            rationale="Peak-area crystallinity should not dominate when the amorphous split is still fragile.",
        ),
        EvidenceConstraint(
            name="peak_width_nonphysical",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Peak widths look implausible for a physical crystal family.",
            field="peaks",
            rationale="Zero, negative, or absurdly broad widths usually indicate a bad fit.",
        ),
        EvidenceConstraint(
            name="offset_sensitive_solution",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="The fit appears sensitive to a non-zero 2θ offset.",
            field="two_theta_offset",
            rationale="A material offset should be resolved before claiming a stable crystal geometry.",
        ),
        EvidenceConstraint(
            name="crystallinity_without_peak_support",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Crystallinity is being claimed without enough peak support.",
            field="Xc_pct",
            rationale="Xc should be backed by a stable peak family, not only by fit smoothness.",
        ),
        EvidenceConstraint(
            name="size_without_multi_peak_support",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Scherrer size is not trustworthy without at least two resolved peaks.",
            field="D_Scherrer_nm",
            rationale="Crystallite size needs more than one peak to be a robust estimate.",
        ),
        EvidenceConstraint(
            name="scherrer_trend_without_multi_peak_support",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Scherrer trend is not trustworthy without repeated multi-peak support.",
            field="D_trend_support_score",
            rationale="Temperature-dependent crystallite size should stay tied to repeated resolved peaks.",
        ),
        EvidenceConstraint(
            name="scherrer_jump_single_frame",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Scherrer size jumps too sharply in a single frame.",
            field="D_jump_single_frame_count",
            rationale="A paper-grade D trend should not hinge on a single unstable frame.",
        ),
        EvidenceConstraint(
            name="scherrer_dominated_by_peak_width_noise",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Scherrer trend is dominated by peak-width noise rather than a stable trend.",
            field="D_slope_distribution",
            rationale="When width noise dominates, the size trend is not yet robust enough for interpretation.",
        ),
        EvidenceConstraint(
            name="scherrer_instrument_broadening_unresolved",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Instrument broadening is not clearly modeled, so Scherrer size remains provisional.",
            field="instrument_broadening_present",
            rationale="Scherrer size should be interpreted with instrument broadening in mind.",
        ),
        EvidenceConstraint(
            name="scherrer_conflicts_with_peak_family_tracking",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Scherrer trend conflicts with unstable peak-family tracking.",
            field="FWHM_values_by_family",
            rationale="Size claims need the same peak families to stay trackable across temperature.",
        ),
        EvidenceConstraint(
            name="scherrer_unphysical_temperature_trend",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Scherrer trend oscillates too much to be treated as a physical temperature trend.",
            field="D_values_nm",
            rationale="A physically meaningful size trend should not bounce frame to frame without support.",
        ),
        EvidenceConstraint(
            name="fit_quality_vs_phys",
            kind="soft_warn",
            source="WAXS",
            severity="WARN",
            description="Fit score is not sufficient without physical support.",
            field="r_squared",
            rationale="A fit-only score can overstate confidence.",
        ),
    )
