from __future__ import annotations

from typing import Any

from .analysis_evidence_common import _collect_source_fields
from .analysis_evidence_models import AnalysisEvidence


def finalize_analysis_evidence(
    *,
    technique_key: str,
    summary: str,
    fit_evidence: dict[str, Any],
    physical_evidence: dict[str, Any],
    residual_evidence: dict[str, Any],
    feature_evidence: dict[str, Any],
    signal_evidence: dict[str, Any],
    peak_evidence: dict[str, Any],
    assignment_evidence: dict[str, Any],
    reference_evidence: dict[str, Any],
    background_evidence: dict[str, Any],
    phase_evidence: dict[str, Any],
    transform_evidence: dict[str, Any],
    structure_evidence: dict[str, Any],
    raw_structure_evidence: dict[str, Any],
    batch_evidence: dict[str, Any],
    condition_evidence: dict[str, Any],
    stability_evidence: dict[str, Any],
    symptoms: list[dict[str, Any]],
    risk_flags: list[str],
    confidence_signals: list[dict[str, Any]],
    actionable_symptoms: list[str],
    constraints: list[dict[str, Any]],
    constraint_summary: dict[str, Any],
    validation: dict[str, Any],
) -> AnalysisEvidence:
    return AnalysisEvidence(
        technique=technique_key,
        summary=summary,
        fit_evidence=fit_evidence,
        physical_evidence=physical_evidence,
        residual_evidence=residual_evidence,
        feature_evidence=feature_evidence,
        signal_evidence=signal_evidence,
        peak_evidence=peak_evidence,
        assignment_evidence=assignment_evidence,
        reference_evidence=reference_evidence,
        background_evidence=background_evidence,
        phase_evidence=phase_evidence,
        transform_evidence=transform_evidence,
        structure_evidence=structure_evidence,
        raw_structure_evidence=raw_structure_evidence,
        batch_evidence=batch_evidence,
        condition_evidence=condition_evidence,
        stability_evidence=stability_evidence,
        symptoms=symptoms,
        risk_flags=list(dict.fromkeys(risk_flags)),
        confidence_signals=confidence_signals,
        actionable_symptoms=actionable_symptoms,
        constraints=constraints,
        constraint_summary=constraint_summary,
        cross_validation=validation.get("cross_validation", {}) if isinstance(validation.get("cross_validation", {}), dict) else {},
        source_fields=_collect_source_fields(
            fit_evidence=fit_evidence,
            physical_evidence=physical_evidence,
            feature_evidence=feature_evidence,
            residual_evidence=residual_evidence,
            signal_evidence=signal_evidence,
            peak_evidence=peak_evidence,
            reference_evidence=reference_evidence,
            background_evidence=background_evidence,
            phase_evidence=phase_evidence,
            transform_evidence=transform_evidence,
            structure_evidence=structure_evidence,
            raw_structure_evidence=raw_structure_evidence,
            batch_evidence=batch_evidence,
            condition_evidence=condition_evidence,
            stability_evidence=stability_evidence,
            symptoms=symptoms,
        ),
    )
