from __future__ import annotations

from .analysis_evidence_constraint_models import EvidenceConstraint, _inventory


def _ir_constraint_inventory() -> list[EvidenceConstraint]:
    return _inventory(
        EvidenceConstraint(
            name="assignment_confidence",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="Polymer assignment confidence should be tracked explicitly.",
            field="polymer_score",
            rationale="Peak matching needs a confidence layer, not just raw fit.",
        ),
        EvidenceConstraint(
            name="key_band_support_insufficient",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="Reference-band coverage is too weak to support a stable polymer call.",
            field="n_peaks",
            rationale="The agent should not promote a polymer assignment when key bands are still missing.",
        ),
        EvidenceConstraint(
            name="assignment_without_characteristic_bands",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="Assignment exists, but characteristic bands are not yet consistently matched.",
            field="assignment_confidence",
            rationale="Assignment confidence should agree with key-band coverage.",
        ),
        EvidenceConstraint(
            name="baseline_sensitive_assignment",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="Polymer assignment depends too much on baseline or normalization settings.",
            field="baseline_method",
            rationale="Baseline stability should be resolved before the agent tries to strengthen the call.",
        ),
        EvidenceConstraint(
            name="baseline_drift_low_wn",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="The low-wavenumber edge is drifting and should be stabilized first.",
            field="residual_type",
            rationale="Low-wavenumber drift usually points to baseline instability.",
        ),
        EvidenceConstraint(
            name="baseline_drift_high_wn",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="The high-wavenumber edge is drifting and should be stabilized first.",
            field="residual_type",
            rationale="High-wavenumber drift usually points to normalization instability.",
        ),
        EvidenceConstraint(
            name="key_band_mismatch",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="Characteristic bands are locally mismatched against the observed spectrum.",
            field="residual_type",
            rationale="Band identity should stabilize before the polymer call is promoted.",
        ),
        EvidenceConstraint(
            name="crowded_band_underfit",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="Crowded bands are not being separated cleanly enough for a stable assignment.",
            field="residual_type",
            rationale="Crowded bands need a separation pass before the conclusion is strengthened.",
        ),
        EvidenceConstraint(
            name="over_smoothed_weak_bands",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="Weak bands are likely being smoothed away before they can support the assignment.",
            field="residual_type",
            rationale="Over-smoothing can erase the weak bands needed for a credible call.",
        ),
        EvidenceConstraint(
            name="normalization_bias",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="Normalization is biasing the relative band balance.",
            field="residual_type",
            rationale="Normalization should stabilize before peak thresholds are adjusted again.",
        ),
        EvidenceConstraint(
            name="noise_dominant",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="The residual is dominated by noise rather than a localized mismatch.",
            field="residual_type",
            rationale="Noise-dominant spectra should be smoothed before band thresholds are changed.",
        ),
        EvidenceConstraint(
            name="weak_peak_only_support",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="Peak detection alone is not enough to support a confident IR conclusion.",
            field="n_peaks",
            rationale="The evidence needs matching reference bands, not just a visible peak count.",
        ),
        EvidenceConstraint(
            name="overcrowded_band_separation_unstable",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="Crowded bands or wide fit windows make the local band separation unstable.",
            field="peak_distance",
            rationale="The next tuning round should narrow the band separation problem before pushing confidence up.",
        ),
        EvidenceConstraint(
            name="polymer_score_without_assignment_support",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="Polymer score is present but not backed by enough assigned peaks or key bands.",
            field="polymer_score",
            rationale="A score alone should not override weak assignment support.",
        ),
        EvidenceConstraint(
            name="crystallinity_index_without_band_support",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="Crystallinity index is being reported without enough supporting bands.",
            field="Xc_pct",
            rationale="IR crystallinity should stay tentative until the band support chain is stable.",
        ),
        EvidenceConstraint(
            name="ir_xc_uncalibrated",
            kind="soft_warn",
            source="IR",
            severity="WARN",
            description="IR crystallinity is an uncalibrated band index.",
            field="Xc_calibration_status",
            rationale="Uncalibrated IR ratios should stay diagnostic and not be compared as calibrated crystallinity.",
        ),
        EvidenceConstraint(
            name="peak_structure",
            kind="evidence_only",
            source="IR",
            severity="INFO",
            description="Peak count and band coverage are evidence signals.",
            field="n_peaks",
            rationale="Use them as supporting evidence for the assignment path.",
        ),
    )
