from __future__ import annotations

from .analysis_evidence_constraint_models import EvidenceConstraint, _inventory


def _saxs_constraint_inventory() -> list[EvidenceConstraint]:
    return _inventory(
        EvidenceConstraint(
            name="beamstop_contamination",
            kind="hard_fail",
            source="SAXS",
            severity="ERROR",
            description="Beam-stop contamination can invalidate low-q interpretation.",
            field="beam_stop_contaminated",
            rationale="low-q / q* evidence is not reliable when the beamstop intrudes.",
        ),
        EvidenceConstraint(
            name="mask_truncated",
            kind="soft_warn",
            source="SAXS",
            severity="WARN",
            description="Effective q-min is truncated and reduces low-q confidence.",
            field="mask_truncated",
            rationale="Long-period evidence becomes weaker when q-range is cut.",
        ),
        EvidenceConstraint(
            name="low_peak_snr",
            kind="evidence_only",
            source="SAXS",
            severity="INFO",
            description="Lamellar peak SNR is a confidence signal, not a hard gate.",
            field="q_peak_snr",
            rationale="Use it to weight confidence, not to replace the fit score.",
        ),
        EvidenceConstraint(
            name="l_consistency",
            kind="soft_warn",
            source="SAXS",
            severity="WARN",
            description="Bragg and correlation long-period estimates should stay close.",
            field="L_bragg",
            rationale="Cross-check long-period estimates before acceptance.",
        ),
        EvidenceConstraint(
            name="fit_regions_unstable",
            kind="soft_warn",
            source="SAXS",
            severity="WARN",
            description="Peak/correlation fit regions look numerically unstable and often produce misleading figures.",
            field="fit_regions",
            rationale="When multiple fit regions fail together, AI should stop tuning and ask the core path to stabilize first.",
        ),
        EvidenceConstraint(
            name="correlation_over_oscillation",
            kind="soft_warn",
            source="SAXS",
            severity="WARN",
            description="Correlation or IDF curves oscillate too densely to support a trustworthy lamellar interpretation.",
            field="fit_regions",
            rationale="Dense oscillation usually means q-range, smoothing, or preprocessing is dominating the shape.",
        ),
        EvidenceConstraint(
            name="missing_condition_axis",
            kind="hard_fail",
            source="SAXS",
            severity="ERROR",
            description="In-situ SAXS series is missing reliable condition values, so trend plots are not scientifically trustworthy.",
            field="condition_value",
            rationale="If the temperature/strain axis is unknown, the agent should not optimize toward that sequence trend.",
        ),
        EvidenceConstraint(
            name="strain_axis_low_confidence",
            kind="soft_warn",
            source="SAXS",
            severity="WARN",
            description="The strain axis is present but still low-confidence.",
            field="condition_confidence",
            rationale="Sequence interpretation should remain provisional until the strain axis stabilizes.",
        ),
        EvidenceConstraint(
            name="strain_sequence_nonmonotonic",
            kind="soft_warn",
            source="SAXS",
            severity="WARN",
            description="The strain sequence is not strictly monotonic.",
            field="strain_pct",
            rationale="Stretching order must be clear before a trend is interpreted.",
        ),
        EvidenceConstraint(
            name="strain_duplicate_frames",
            kind="soft_warn",
            source="SAXS",
            severity="WARN",
            description="Duplicate strain frames weaken sequence continuity.",
            field="condition_value",
            rationale="Duplicate conditions can fake smooth trends.",
        ),
        EvidenceConstraint(
            name="low_q_void_dominant",
            kind="soft_warn",
            source="SAXS",
            severity="WARN",
            description="Low-q void or upturn evidence dominates the strain chain.",
            field="phi_void",
            rationale="Void-dominated low-q shapes should be separated before lamellar trends are trusted.",
        ),
        EvidenceConstraint(
            name="strain_void_lamellar_conflict",
            kind="soft_warn",
            source="SAXS",
            severity="WARN",
            description="Void growth conflicts with the lamellar long-period interpretation under strain.",
            field="invariant_Q_rel",
            rationale="A single lamellar explanation is too weak when void evidence rises at the same time.",
        ),
        EvidenceConstraint(
            name="lamellar_anchor_lost_under_strain",
            kind="soft_warn",
            source="SAXS",
            severity="WARN",
            description="The lamellar anchor is unstable across the strain series.",
            field="L_bragg",
            rationale="The strain trend needs a stable L anchor before comparison across frames.",
        ),
        EvidenceConstraint(
            name="qstar_rel_without_lamellar_support",
            kind="soft_warn",
            source="SAXS",
            severity="WARN",
            description="Q* relative values are present, but lamellar support is weak.",
            field="invariant_Q_rel",
            rationale="Q* normalization should not outrun the long-period evidence chain.",
        ),
        EvidenceConstraint(
            name="orientation_shift_breaks_lamellar_comparison",
            kind="soft_warn",
            source="SAXS",
            severity="WARN",
            description="Orientation changes are large enough to weaken frame-to-frame lamellar comparison.",
            field="f_Herman",
            rationale="Changing orientation can move the apparent lamellar support even when Q* still looks tidy.",
        ),
    )
