from __future__ import annotations

from .analysis_evidence_constraint_models import EvidenceConstraint, _inventory


def _dsc_constraint_inventory() -> list[EvidenceConstraint]:
    return _inventory(
        EvidenceConstraint(
            name="quality_floor",
            kind="hard_fail",
            source="DSC",
            severity="ERROR",
            description="Low DSC quality score should not be promoted as a valid candidate.",
            field="quality_score",
            rationale="File-level fits need a minimum quality gate.",
        ),
        EvidenceConstraint(
            name="multi_scan_inconsistent",
            kind="evidence_only",
            source="DSC",
            severity="INFO",
            description="Aggregate scan metrics matter more than one local fit score.",
            field="scan_r_squared",
            rationale="Use the file-level median as the main evidence stream.",
        ),
        EvidenceConstraint(
            name="baseline_sensitive_result",
            kind="soft_warn",
            source="DSC",
            severity="WARN",
            description="Baseline-sensitive DSC output should stay provisional until drift-like residuals settle.",
            field="quality_score",
            rationale="A plausible number is not enough when the thermal baseline is still steering the result.",
        ),
        EvidenceConstraint(
            name="Tg_without_DCp_step",
            kind="soft_warn",
            source="DSC",
            severity="WARN",
            description="A reported Tg without a visible Cp-step should stay evidence-limited.",
            field="Tg_C",
            rationale="Tg claims should be supported by a measurable heat-capacity step.",
        ),
        EvidenceConstraint(
            name="Tg_outside_supported_window",
            kind="soft_warn",
            source="DSC",
            severity="WARN",
            description="Tg outside the configured search window should not be promoted as stable.",
            field="Tg_C",
            rationale="A glass-transition claim needs to stay inside the search bounds that produced it.",
        ),
        EvidenceConstraint(
            name="melting_without_supported_event",
            kind="soft_warn",
            source="DSC",
            severity="WARN",
            description="Reported melting should map to a supported thermal event, not only a fitted scalar.",
            field="Tm_peak_C",
            rationale="Tm should remain anchored to an actual endothermic event.",
        ),
        EvidenceConstraint(
            name="cold_crystallization_conflicts_with_melting",
            kind="soft_warn",
            source="DSC",
            severity="WARN",
            description="Cold crystallisation should stay thermally separated from melting on heating scans.",
            field="Tcc_peak_C",
            rationale="Overlapping event windows weaken the thermodynamic interpretation.",
        ),
        EvidenceConstraint(
            name="event_polarity_conflict",
            kind="soft_warn",
            source="DSC",
            severity="WARN",
            description="Event polarity should match the exo-up convention used by the scan.",
            field="peak_components",
            rationale="A sign mismatch means the event is not yet physically consistent.",
        ),
        EvidenceConstraint(
            name="peak_components_too_sparse",
            kind="soft_warn",
            source="DSC",
            severity="WARN",
            description="Too few supported peak components make DSC conclusions fragile.",
            field="peak_components",
            rationale="Thermal claims need at least one supported event component.",
        ),
        EvidenceConstraint(
            name="peak_width_nonphysical",
            kind="soft_warn",
            source="DSC",
            severity="WARN",
            description="Non-physical DSC event widths usually indicate unstable windows or baseline handling.",
            field="peak_components",
            rationale="Event widths should stay positive and within a realistic thermal window.",
        ),
        EvidenceConstraint(
            name="multi_scan_inconsistent",
            kind="soft_warn",
            source="DSC",
            severity="WARN",
            description="Different scans disagree too much to support a stable file-level DSC conclusion.",
            field="scan_r_squared",
            rationale="File-level confidence should fall when valid scans diverge sharply.",
        ),
        EvidenceConstraint(
            name="crystallinity_without_event_support",
            kind="soft_warn",
            source="DSC",
            severity="WARN",
            description="Crystallinity estimates should stay tied to supported thermal events.",
            field="Xc_pct",
            rationale="Xc should not outrun the melt / cold-crystallisation evidence chain.",
        ),
        EvidenceConstraint(
            name="dsc_baseline_sensitive_xc",
            kind="soft_warn",
            source="DSC",
            severity="WARN",
            description="DSC crystallinity is sensitive to baseline or integration boundaries.",
            field="baseline_sensitivity_pct",
            rationale="Xc should be downgraded when small baseline changes materially alter enthalpy.",
        ),
        EvidenceConstraint(
            name="quality_score_without_event_support",
            kind="soft_warn",
            source="DSC",
            severity="WARN",
            description="A good DSC score is not enough when there is no supported thermal event underneath it.",
            field="quality_score",
            rationale="Fit quality should confirm event support, not replace it.",
        ),
    )
