"""HTML report generator for PolyNexus analysis results.

Generates a self-contained HTML report summarising results from
all techniques, with embedded figures and parameter tables.
"""

import logging
logger = logging.getLogger(__name__)

import os, json
from datetime import datetime
from typing import Dict, List, Any, Optional


# ---------------------------------------------------------------------------
#  HTML template
# ---------------------------------------------------------------------------

REPORT_CSS = """
body {
    font-family: 'Segoe UI', 'PingFang SC', sans-serif;
    background: #0f1117; color: #e8eaf0; margin: 0; padding: 20px;
}
.header {
    background: linear-gradient(90deg, #0d1021, #151828);
    border-bottom: 1px solid #2d3150; padding: 20px 30px; margin: -20px -20px 30px -20px;
}
.header h1 {
    background: linear-gradient(135deg, #00c8d4, #4f8ef7);
    -webkit-background-clip: text; -webkit-text-fill-color: transparent;
    font-size: 24px; margin: 0;
}
.header .meta { color: #8b92a8; font-size: 12px; margin-top: 5px; }
.section {
    background: #1a1d2e; border: 1px solid #2d3150; border-radius: 8px;
    padding: 20px; margin-bottom: 24px;
}
.section h2 { color: #4f8ef7; font-size: 18px; margin: 0 0 15px 0;
    border-bottom: 1px solid #2d3150; padding-bottom: 10px; }
.section h3 { color: #00c8d4; font-size: 14px; margin: 15px 0 8px 0; }
table {
    width: 100%; border-collapse: collapse; margin: 10px 0;
    font-size: 12px;
}
th {
    background: #222538; color: #8b92a8; text-align: left;
    padding: 8px 12px; border-bottom: 2px solid #2d3150;
    font-weight: 600; text-transform: uppercase; font-size: 10px;
}
td {
    padding: 6px 12px; border-bottom: 1px solid #2d3150; color: #e8eaf0;
}
tr:hover td { background: #2a2e45; }
.figure-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 16px; margin: 15px 0; }
.figure-grid img { width: 100%; border-radius: 4px; border: 1px solid #2d3150; }
.figure-grid .caption { color: #8b92a8; font-size: 10px; text-align: center; margin-top: 4px; }
.crystallinity-bar {
    display: inline-block; height: 20px; border-radius: 4px;
    background: linear-gradient(90deg, #4f8ef7, #00c8d4);
    margin-right: 8px; min-width: 30px;
}
.warning { color: #e69f00; }
.success { color: #00b87c; }
"""


REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PolyNexus Report — {project_name}</title>
    <style>{css}</style>
</head>
<body>
    <div class="header">
        <h1>PolyNexus Analysis Report</h1>
        <div class="meta">
            Project: {project_name} | Generated: {timestamp}
            | Techniques: {techniques}
        </div>
    </div>

    {sections}

    <div class="section">
        <h2>Summary</h2>
        <p>Report generated by PolyNexus v1.0.</p>
    </div>
</body>
</html>
"""


# ---------------------------------------------------------------------------
#  Section builders
# ---------------------------------------------------------------------------

def _build_dsc_section(results):
    """Build DSC results section."""
    if not results:
        return ""

    rows = []
    for r in results:
        label = getattr(r, 'label', 'Sample')
        params = getattr(r, 'parameters', {})
        rows.append(f"""
        <tr>
            <td>{label}</td>
            <td>{params.get('Tg_C', '—')}</td>
            <td>{params.get('Tm_peak_C', '—')}</td>
            <td>{params.get('DHm_Jg', '—')}</td>
            <td><span class="crystallinity-bar" style="width:{params.get('Xc_pct', 0)}px"></span>
                {params.get('Xc_pct', '—')}%</td>
            <td>{params.get('quality_score', '—')}</td>
        </tr>""")

    html = f"""
    <div class="section">
        <h2>DSC — Differential Scanning Calorimetry</h2>
        <table>
            <tr>
                <th>Sample</th><th>Tg (°C)</th><th>Tm (°C)</th>
                <th>ΔHm (J/g)</th><th>Xc</th><th>Quality</th>
            </tr>
            {''.join(rows)}
        </table>
    </div>"""
    return html


def _build_waxs_section(results):
    if not results:
        return ""
    rows = []
    for r in results:
        label = getattr(r, 'label', 'Sample')
        params = getattr(r, 'parameters', {})
        rows.append(f"""
        <tr>
            <td>{label}</td>
            <td>{params.get('n_peaks', '—')}</td>
            <td>{params.get('Xc_pct', '—')}%</td>
            <td>{params.get('D_Scherrer_nm', '—')} nm</td>
            <td>{params.get('crystal_system', '—')}</td>
            <td>{params.get('r_squared', '—')}</td>
        </tr>""")

    return f"""
    <div class="section">
        <h2>WAXS — Wide-Angle X-ray Scattering</h2>
        <table>
            <tr>
                <th>Sample</th><th>Peaks</th><th>Xc</th>
                <th>D (Scherrer)</th><th>Crystal System</th><th>R²</th>
            </tr>
            {''.join(rows)}
        </table>
    </div>"""


def _build_saxs_section(results):
    if not results:
        return ""
    rows = []
    for r in results:
        label = getattr(r, 'label', 'Sample')
        params = getattr(r, 'parameters', {})
        rows.append(f"""
        <tr>
            <td>{label}</td>
            <td>{params.get('L_nm', '—')}</td>
            <td>{params.get('lc_nm', '—')}</td>
            <td>{params.get('la_nm', '—')}</td>
            <td>{params.get('Q_inv', '—')}</td>
        </tr>""")

    return f"""
    <div class="section">
        <h2>SAXS — Small-Angle X-ray Scattering</h2>
        <table>
            <tr>
                <th>Sample</th><th>L (nm)</th><th>lc (nm)</th>
                <th>la (nm)</th><th>Q*</th>
            </tr>
            {''.join(rows)}
        </table>
    </div>"""


def _build_ir_section(results):
    if not results:
        return ""
    rows = []
    for r in results:
        label = getattr(r, 'label', 'Sample')
        params = getattr(r, 'parameters', {})
        rows.append(f"""
        <tr>
            <td>{label}</td>
            <td>{params.get('n_peaks', '—')}</td>
            <td>{params.get('Xc_pct', '—')}</td>
            <td>{params.get('n_matches', '—')}</td>
            <td>{params.get('r_squared', '—')}</td>
        </tr>""")

    return f"""
    <div class="section">
        <h2>IR — Infrared Spectroscopy</h2>
        <table>
            <tr>
                <th>Sample</th><th>Peaks</th><th>Xc Index</th>
                <th>DFT Matches</th><th>R²</th>
            </tr>
            {''.join(rows)}
        </table>
    </div>"""


def _build_nmr_section(results):
    if not results:
        return ""
    rows = []
    for r in results:
        label = getattr(r, 'label', 'Sample')
        params = getattr(r, 'parameters', {})
        rows.append(f"""
        <tr>
            <td>{label}</td>
            <td>{params.get('n_peaks', '—')}</td>
            <td>{params.get('Xc_pct', '—')}%</td>
            <td>{params.get('n_matches', '—')}</td>
            <td>{params.get('r_squared', '—')}</td>
        </tr>""")

    return f"""
    <div class="section">
        <h2>NMR — Solid-State Nuclear Magnetic Resonance</h2>
        <table>
            <tr>
                <th>Sample</th><th>Peaks</th><th>Xc</th>
                <th>DFT Matches</th><th>R²</th>
            </tr>
            {''.join(rows)}
        </table>
    </div>"""


def _build_figures_section(output_dir):
    """Embed figures from output directory as base64."""
    fig_dir = os.path.join(output_dir, 'figures')
    if not os.path.isdir(fig_dir):
        return ""

    figs = sorted([f for f in os.listdir(fig_dir)
                   if f.lower().endswith(('.svg', '.png'))])
    if not figs:
        return ""

    items = []
    for fn in figs[:12]:  # Limit to 12 figures
        fp = os.path.join(fig_dir, fn)
        # For SVG, embed directly; for PNG, base64 encode
        if fn.lower().endswith('.svg'):
            try:
                with open(fp, 'r', encoding='utf-8') as f:
                    svg_content = f.read()
                # Extract just the <svg> tag
                import re
                svg_match = re.search(r'<svg.*?</svg>', svg_content, re.DOTALL)
                if svg_match:
                    items.append(
                        f'<div>{svg_match.group(0)}'
                        f'<div class="caption">{fn}</div></div>')
            except Exception:
                logger.warning("Report SVG figure embedding failed.", exc_info=True)
        else:
            import base64
            try:
                with open(fp, 'rb') as f:
                    b64 = base64.b64encode(f.read()).decode()
                ext = os.path.splitext(fn)[1][1:]
                items.append(
                    f'<div><img src="data:image/{ext};base64,{b64}" />'
                    f'<div class="caption">{fn}</div></div>')
            except Exception:
                logger.warning("Report raster figure embedding failed.", exc_info=True)

    if not items:
        return ""

    return f"""
    <div class="section">
        <h2>Figures</h2>
        <div class="figure-grid">
            {''.join(items)}
        </div>
    </div>"""


def _build_ir_section(results):
    if not results:
        return ""

    rows = []
    temp2d_rows = []
    for r in results:
        label = r.get("label", "Sample") if isinstance(r, dict) else getattr(r, "label", "Sample")
        params = r.get("parameters", {}) if isinstance(r, dict) else getattr(r, "parameters", {})
        analysis_evidence = r.get("analysis_evidence", {}) if isinstance(r, dict) else getattr(r, "analysis_evidence", {})
        if not isinstance(params, dict):
            params = {}
        if not isinstance(analysis_evidence, dict):
            analysis_evidence = {}
        feature = analysis_evidence.get("feature_evidence", {}) if isinstance(analysis_evidence.get("feature_evidence"), dict) else {}
        temp2d = feature.get("temperature_2d_evidence", {}) if isinstance(feature.get("temperature_2d_evidence"), dict) else {}
        if isinstance(temp2d, dict) and temp2d:
            temp2d_rows.append((label, temp2d))
        rows.append(f"""
        <tr>
            <td>{label}</td>
            <td>{params.get('n_peaks', 'N/A')}</td>
            <td>{params.get('Xc_pct', 'N/A')}</td>
            <td>{params.get('n_matches', 'N/A')}</td>
            <td>{params.get('r_squared', 'N/A')}</td>
        </tr>""")

    temp2d_section = ""
    if temp2d_rows:
        temp2d_html_rows = []
        for label, temp2d in temp2d_rows[:8]:
            seq_status = "ready" if float(temp2d.get("sequence_axis_score", 0.0) or 0.0) >= 0.75 else "review"
            status = "paper-ready" if temp2d.get("paper_conclusion_ready") else ("tentative" if temp2d.get("interpretation_ready") else "diagnostic")
            temp2d_html_rows.append(f"""
            <tr>
                <td>{label}</td>
                <td>{seq_status}</td>
                <td>{temp2d.get('matrix_quality_score', 'N/A')}</td>
                <td>{temp2d.get('cos_signal_score', 'N/A')}</td>
                <td>{status}</td>
            </tr>""")
        temp2d_section = f"""
    <div class="section">
        <h2>IR Temperature 2D</h2>
        <table>
            <tr>
                <th>Sample</th><th>Sequence</th><th>Matrix</th>
                <th>Correlation</th><th>Status</th>
            </tr>
            {''.join(temp2d_html_rows)}
        </table>
    </div>"""

    return f"""
    <div class="section">
        <h2>IR - Infrared Spectroscopy</h2>
        <table>
            <tr>
                <th>Sample</th><th>Peaks</th><th>Xc Index</th>
                <th>DFT Matches</th><th>R2</th>
            </tr>
            {''.join(rows)}
        </table>
    </div>{temp2d_section}"""


# ---------------------------------------------------------------------------
#  Main report generator
# ---------------------------------------------------------------------------

def generate_report(project_name="Polymer Analysis",
                    output_dir="",
                    dsc_results=None,
                    waxs_results=None,
                    saxs_results=None,
                    ir_results=None,
                    nmr_results=None,
                    joint_results=None,
                    ) -> str:
    """Generate a complete HTML report.

    Parameters
    ----------
    project_name : str
    output_dir : str
        Directory containing figures/ subfolder.
    *_results : list of result objects
        Results from each technique engine.

    Returns
    -------
    str : Complete HTML report.
    """
    sections = []

    # Technique sections
    if dsc_results:
        sections.append(_build_dsc_section(dsc_results))
    if waxs_results:
        sections.append(_build_waxs_section(waxs_results))
    if saxs_results:
        sections.append(_build_saxs_section(saxs_results))
    if ir_results:
        sections.append(_build_ir_section(ir_results))
    if nmr_results:
        sections.append(_build_nmr_section(nmr_results))

    # Joint analysis
    if joint_results:
        rows = []
        for j in joint_results:
            params = getattr(j, 'parameters', {})
            rows.append(f"""
            <tr>
                <td>{params.get('label', '—')}</td>
                <td>{params.get('Xc_dsc_pct', '—')}%</td>
                <td>{params.get('Xc_waxs_pct', '—')}%</td>
                <td>{params.get('Xc_saxs_pct', '—')}%</td>
                <td><strong>{params.get('Xc_consensus', '—')}%</strong></td>
            </tr>""")
        sections.append(f"""
        <div class="section">
            <h2>Cross-Technique Comparison</h2>
            <table>
                <tr>
                    <th>Sample</th><th>Xc DSC</th><th>Xc WAXS</th>
                    <th>Xc SAXS</th><th>Consensus</th>
                </tr>
                {''.join(rows)}
            </table>
        </div>""")

    # Figures
    if output_dir:
        sections.append(_build_figures_section(output_dir))

    # Technique summary
    techniques = []
    for name, results in [('DSC', dsc_results), ('WAXS', waxs_results),
                            ('SAXS', saxs_results), ('IR', ir_results),
                            ('NMR', nmr_results)]:
        if results:
            techniques.append(name)

    html = REPORT_TEMPLATE.format(
        project_name=project_name,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        techniques=', '.join(techniques) if techniques else 'None',
        sections=''.join(sections),
        css=REPORT_CSS,
    )

    return html


def save_report(html, output_dir, filename="polynexus_report.html"):
    """Save HTML report to disk."""
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, filename)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)
    return path
