"""IR periodic DFT/DFPT interface (IR-D).

Generates input files and parses output for periodic-boundary-condition
IR calculations using:
    - CASTEP (DFPT linear response)
    - VASP (finite differences + Born effective charges)
    - Quantum ESPRESSO (ph.x DFPT)
    - CP2K (vibrational analysis)

For crystalline polymers, periodic DFT properly accounts for:
    - LO-TO splitting at Gamma point
    - Intermolecular coupling in the crystal lattice
    - Correct IR intensities from Born effective charges
"""

from typing import Dict, List, Optional


# ---------------------------------------------------------------------------
#  CASTEP input generator
# ---------------------------------------------------------------------------

def generate_castep_phonon_input(cell_file_content, kpoint_mp=(1,1,1),
                                  functional="PBE",
                                  cutoff_energy_eV=600,
                                  ) -> str:
    """Generate CASTEP .param file for DFPT phonon/IR calculation.

    Requires a .cell file with atomic positions (generated separately).

    Parameters
    ----------
    cell_file_content : str
        Path to or content of the .cell file.
    kpoint_mp : tuple
        Monkhorst-Pack k-point grid.
    functional : str
        'PBE', 'PBEsol', 'LDA', 'PW91', 'WC', 'RPBE'.
    cutoff_energy_eV : float

    Returns
    -------
    str : .param file content
    """
    kpt_str = f"{kpoint_mp[0]} {kpoint_mp[1]} {kpoint_mp[2]}"

    param = f"""# CASTEP DFPT Phonon + IR calculation
# Generated by PolyNexus IR-D module

task = phonon

# Exchange-correlation
xc_functional = {functional}

# Basis set
cut_off_energy = {cutoff_energy_eV} eV

# k-points
kpoint_mp_grid = {kpt_str}

# Phonon calculation
phonon_calculate_ir_intensities = true
phonon_calculate_raman_intensities = false
phonon_fine_method = interpolate
phonon_fine_kpath_spacing = 0.02
phonon_fine_qpath_spacing = 0.02

# Output
write_formatted_dos = true
phonon_write_ eigenvectors = true
write_cell_structure = true

# Convergence
elec_energy_tol = 1e-8 eV/atom
geom_energy_tol = 1e-5 eV/atom
geom_force_tol = 1e-3 eV/A
geom_stress_tol = 0.05 GPa
geom_disp_tol = 1e-3 A

# SCF
max_scf_cycles = 200
mix_history_length = 20
mix_charge_amp = 0.5

# Smearing for metallic systems (not needed for most polymers)
# metals_method = dm
# smearing_width = 0.1 eV
"""
    return param.strip()


# ---------------------------------------------------------------------------
#  VASP INCAR generator for vibrational analysis
# ---------------------------------------------------------------------------

def generate_vasp_vib_incar(encut=500, ediff=1e-7, ismear=0, sigma=0.05,
                             ibrion=5, nfree=2, potim=0.015, nsw=1):
    """Generate VASP INCAR for finite-difference vibrational analysis.

    IBRION=5: compute Hessian by finite differences (no cell relaxation)
    IBRION=6: compute Hessian by finite differences (with symmetry)
    NFREE=2: central differences (more accurate)

    For IR intensities, also compute Born effective charges:
        LEPSILON = .TRUE.
    """
    incar = f"""# VASP Vibrational Analysis INCAR
# Generated by PolyNexus IR-D module

# Electronic
ENCUT = {encut}
EDIFF = {ediff}
PREC = Accurate

# Smearing
ISMEAR = {ismear}
SIGMA = {sigma}

# Vibrational calculation (finite differences)
IBRION = {ibrion}
NFREE = {nfree}
POTIM = {potim}
NSW = {nsw}

# IR intensities via Born effective charges
LEPSILON = .TRUE.

# Output
LREAL = .FALSE.
LORBIT = 11

# Parallelisation
# NCORE = 4
# KPAR = 2
"""
    return incar.strip()


# ---------------------------------------------------------------------------
#  Quantum ESPRESSO ph.x input generator
# ---------------------------------------------------------------------------

def generate_qe_phonon_input(prefix="polymer", outdir="./tmp",
                              alpha_mix=0.7, tr2_ph=1e-12):
    """Generate QE ph.x input for Gamma-point phonon/IR calculation.

    Requires a prior scf calculation with pw.x.
    """
    ph_input = f"""Phonon calculation at Gamma
 &inputph
  prefix = '{prefix}'
  outdir = '{outdir}'
  tr2_ph = {tr2_ph}
  alpha_mix({alpha_mix}) = {alpha_mix}
  ldisp = .false.
  trans = .true.
  asr = .true.
  epsil = .true.       ! Born effective charges for IR
  fildyn = '{prefix}.dyn'
  fildvscf = '{prefix}.dvscf'
 /
0.0 0.0 0.0   ! q-point: Gamma
"""
    return ph_input.strip()


# ---------------------------------------------------------------------------
#  LO-TO splitting correction
# ---------------------------------------------------------------------------

def correct_lo_to_splitting(frequencies, born_charges, epsilon_inf,
                            q_direction=(0.001, 0, 0)):
    """Apply LO-TO splitting correction to Gamma-point frequencies.

    In polar crystals, the LO and TO modes at Gamma are split by the
    macroscopic electric field. The splitting depends on the Born
    effective charges and the dielectric tensor.

    Parameters
    ----------
    frequencies : ndarray
        TO frequencies (cm^-1).
    born_charges : ndarray (n_atoms, 3, 3)
    epsilon_inf : ndarray (3, 3)
        High-frequency dielectric tensor.
    q_direction : tuple
        Direction for LO modes.

    Returns
    -------
    dict with 'TO' and 'LO' frequency arrays.
    """
    import numpy as np

    # Simplified: the LO-TO splitting is proportional to
    # (Z* . q)^2 / (q . epsilon_inf . q)  for each mode

    q = np.array(q_direction, dtype=float)
    q_hat = q / np.linalg.norm(q)

    # This is a simplified placeholder — full implementation
    # requires the eigenvector matrix from DFPT output.
    # For now, return TO frequencies unchanged.
    return {
        'TO_cm1': np.asarray(frequencies),
        'LO_cm1': np.asarray(frequencies),  # TODO: apply proper splitting
    }


# ---------------------------------------------------------------------------
#  Symmetry analysis (group theory for IR activity)
# ---------------------------------------------------------------------------

IR_ACTIVE_POINT_GROUPS = {
    # Crystal systems and their IR-active irreducible representations
    "triclinic":    ["Au"],  # C1 or Ci
    "monoclinic":   ["Au", "Bu"],
    "orthorhombic": ["B1u", "B2u", "B3u"],
    "tetragonal":   ["A2u", "Eu"],
    "trigonal":     ["A2u", "Eu"],
    "hexagonal":    ["A2u", "E1u"],
    "cubic":        ["T1u"],
}


def predict_ir_active_modes(space_group_number, n_atoms_per_cell):
    """Predict number of IR-active modes from space group.

    Uses group theory: for a crystal with N atoms per unit cell,
    there are 3N-3 optical modes. The number of IR-active modes
    depends on the point group symmetry.

    Parameters
    ----------
    space_group_number : int
        International space group number (1-230).
    n_atoms_per_cell : int

    Returns
    -------
    dict with {total_modes, ir_active_estimate, point_group_guess}
    """
    total_modes = 3 * n_atoms_per_cell - 3

    # Rough estimates based on space group ranges
    if 1 <= space_group_number <= 2:
        pg = "triclinic"
        n_active = total_modes  # All modes IR-active in C1
    elif 3 <= space_group_number <= 15:
        pg = "monoclinic"
        n_active = total_modes // 2  # Rough
    elif 16 <= space_group_number <= 74:
        pg = "orthorhombic"
        n_active = total_modes // 3
    elif 75 <= space_group_number <= 142:
        pg = "tetragonal"
        n_active = total_modes // 3
    elif 143 <= space_group_number <= 167:
        pg = "trigonal"
        n_active = total_modes // 3
    elif 168 <= space_group_number <= 194:
        pg = "hexagonal"
        n_active = total_modes // 3
    elif 195 <= space_group_number <= 230:
        pg = "cubic"
        n_active = total_modes // 4
    else:
        pg = "unknown"
        n_active = total_modes

    return {
        'total_optical_modes': total_modes,
        'ir_active_estimate': min(n_active, total_modes),
        'point_group': pg,
        'ir_active_representations': IR_ACTIVE_POINT_GROUPS.get(pg, []),
    }


# ---------------------------------------------------------------------------
#  Polymer crystal space group database
# ---------------------------------------------------------------------------

POLYMER_SPACE_GROUPS = {
    "PE":         {"sg": 62, "name": "Pnma", "system": "orthorhombic"},
    "iPP_alpha":  {"sg": 14, "name": "P2_1/c", "system": "monoclinic"},
    "iPP_beta":   {"sg": 182, "name": "P6_322", "system": "hexagonal"},
    "PET":        {"sg": 2, "name": "P-1", "system": "triclinic"},
    "PA6_alpha":  {"sg": 14, "name": "P2_1/c", "system": "monoclinic"},
    "PA6_gamma":  {"sg": 14, "name": "P2_1/a", "system": "monoclinic"},
    "PA66_alpha": {"sg": 2, "name": "P-1", "system": "triclinic"},
    "PVDF_alpha": {"sg": 14, "name": "P2_1/c", "system": "monoclinic"},
    "PVDF_beta":  {"sg": 38, "name": "Cmc2_1", "system": "orthorhombic"},
    "PLLA_alpha": {"sg": 19, "name": "P2_12_12_1", "system": "orthorhombic"},
    "POM":        {"sg": 19, "name": "P2_12_12_1", "system": "orthorhombic"},
    "PEEK":       {"sg": 62, "name": "Pnma", "system": "orthorhombic"},
    "PPS":        {"sg": 62, "name": "Pnma", "system": "orthorhombic"},
    "PTFE":       {"sg": 194, "name": "P6_3/mmc", "system": "hexagonal"},
    "PCL":        {"sg": 19, "name": "P2_12_12_1", "system": "orthorhombic"},
}
